apiVersion: v1
kind: Service
metadata:
  name: argo-app-service
spec:
  selector:
    app: argo-deployment
  ports:
    - name: argo-app-service
      protocol: TCP
      port: 9300
      targetPort: 8080
      nodePort: 30001
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer:
    ingress:
      - hostname: localhost