apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-deployment
  labels:
    app: argo-deployment
  annotations:
    keel.sh/policy: all
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1m"
spec:
  replicas: 3
  revisionHistoryLimit: 0
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: argo-deployment
  template:
    metadata:
      labels:
        app: argo-deployment
    spec:
      containers:
        - name: argo-deployment-pod
          image: ghcr.io/jose1522/test-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 10
      imagePullSecrets:
        - name: docker-basic-auth