apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  image: ghcr.io/jose1522/test-api
  interval: 1m0s
  secretRef:
    name: regcred